name: "Send Logs to Loki"
description: "Aggregate all workflow logs and send them to Loki with injected labels"
inputs:
  loki_endpoint:
    description: "Loki push endpoint"
    required: true
  labels:
    description: "Custom labels for logs (comma-separated key=value pairs)"
    required: false
    default: "job=github-actions"
  github_token:
    description: "GitHub token for API authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        echo "Installing Python dependencies..."
        pip install -r ./send-logs-to-loki/requirements.txt

    - name: Fetch and Push Logs to Loki
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RUN_ID: ${{ github.run_id }}
        LOKI_ENDPOINT: ${{ inputs.loki_endpoint }}
        LABELS: ${{ inputs.labels }}
      run: python3 ./send-logs-to-loki/push_logs.py
